name: qwen3rlhf
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - numpy
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - accelerate
  - transformers
  - peft
  - bitsandbytes
  - datasets
  - deepspeed
  - tqdm
  - sentencepiece
  - protobuf
  - typing-extensions
  - pip:
      - flash-attn
      - trl
      - einops
      - wandb
      - evaluate
      - nltk
      - rouge_score
      - absl-py
      - huggingface_hub==0.34.1
      - tensorboard
      - matplotlib